# Generated by Django 3.1.3 on 2020-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField()),
                ('prefix', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('principal_amt', models.PositiveIntegerField()),
                ('date_of_borrowing', models.DateField()),
                ('duration', models.DurationField()),
                ('int_rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('paid_amt', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
