# Generated by Django 3.1.3 on 2020-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowers',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='int_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
